language: php

php:  
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - SYMFONY_VERSION=2.3.*
        - SYMFONY_PHPUNIT_BRIDGE_VERSION=2.7.*

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* SYMFONY_PHPUNIT_BRIDGE_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.0.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*@dev SYMFONY_PHPUNIT_BRIDGE_VERSION=3.0.*@dev SYMFONY_DEPRECATIONS_HELPER=strict
    allow_failures:
        - env: SYMFONY_VERSION=3.0.*@dev SYMFONY_PHPUNIT_BRIDGE_VERSION=3.0.*@dev SYMFONY_DEPRECATIONS_HELPER=strict

install:
  - composer self-update
  - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require --no-update symfony/form:${SYMFONY_VERSION}
  - composer require --dev --no-update symfony/phpunit-bridge:${SYMFONY_PHPUNIT_BRIDGE_VERSION}
  - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
  - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: phpunit --coverage-clover=clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: helios.ag@gmail.com
